runtime: python312
entrypoint: gunicorn --bind :$PORT core.app:app

env_variables:
  GOOGLE_ANALYTICS_MEASUREMENT_ID: "G-NF6SVCGZDF"
  BOOKING_URL: "https://calendar.app.google/iPH6W8fgvcCws9VA8"
  SITE_URL: "https://www.teraearlywine.com"
  CONTACT_EMAIL: "tera@idea-factory.io"
  CONTACT_BROKER_URL: "https://if-api-898590924009.us-central1.run.app/api/contact-deliveries"
  CONTACT_BROKER_SECRET_SECRET_ID: "CONTACT_BROKER_SECRET"
  SECRET_KEY_SECRET_ID: "SECRET_KEY"
  CONTACT_TURNSTILE_SITE_KEY: "0x4AAAAAAEwpCSBMtk4Jw2lM"
