site_name: Tera Earlywine

nav: 
  - Home: index.md
  - Resume: resume.md
  - References: references.md

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: cyan
  features:
    - content.tabs.link

  highlightjs: true
  hljs_languages:
    - yaml
    - sql
    - python
    - javascript
    - plaintext

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
