site_name: Tera Earlywine

nav: 
  - Home: index.md
  - Resume: resume.md

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: cyan

  highlightjs: true
  hljs_languages:
    - yaml
    - sql
    - python
    - javascript
    - plaintext
