site_name: Tera Earlywine
site_url: https://teraearlywine.github.io/teraearlywine/
nav: 
  - Home: index.md
  - Resume: resume.md

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: cyan
  features:
    - content.tabs.link
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left


  highlightjs: true
  hljs_languages:
    - yaml
    - sql
    - python
    - javascript
    - plaintext

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

plugins:
  - tags

extra:
  version:
    provider: mike

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/