site_name: Tera Earlywine
site_url: https://teraearlywine.com/

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: cyan

  highlightjs: true
  hljs_languages:
    - yaml
    - sql
    - python
